#!/usr/bin/env bash
# A script that displays to infinity and beyond
# Requirement in between each iteration of the loop add sleep 2

trap 'echo "I am invincible!!!"' SIGTERM
while :; do echo "To infinity and beyond"; sleep 2; done
