#!/usr/bin/env bash
# A script that displays the content of the file /etc/passwd
# The script displays:
# username
# user id
# Home directory path for the user

contents="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d":" -f1, 3, 6
done < "$contents"
