#!/usr/bin/env bash
#script that displays Best School 10 times, but for the 9th time, displays Hi using while and if

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
	    echo "Hi"
	    ((i++))
    fi
done

