#!/usr/bin/env bash
# A script that loops from 1 to 10 and displays bad luck at index 4, goodluck at index 8 and best school at other index using while, if, elif and else

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((i++))
done
