#!/usr/bin/env bash
# A script that displays the content of a current directory
# displays only the part of the name after the dash

contents=$(ls)
for i in $contents; do
    echo "$i" | cut -d '-' -f2
done
